spring:
  application:
    name: distribute-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/didispace/SpringCloud-Learning/
          search-paths: Chapter1-1-8/config-repo
          username: username
          password: password
server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/